# Generated by Django 4.2 on 2025-03-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_changepassword_forgotpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='utype',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
